# Generated by Django 5.2.4 on 2025-07-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_required_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='required_skills',
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.TextField(blank=True),
        ),
    ]
